import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="font-[Poppins] bg-pink-50 text-purple-700 scroll-smooth">

      <nav className="fixed top-0 w-full bg-white shadow-md z-50">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <h1 className="font-bold text-xl">Tsuki 🎀</h1>


          <div className="hidden md:flex gap-6 text-sm font-semibold">
            {["home","about","hobbies","skills","gallery","contact"].map((id) => (
              <a key={id} href={`#${id}`} className="hover:text-pink-500">
                {id.charAt(0).toUpperCase() + id.slice(1)}
              </a>
            ))}
          </div>
</div>

         </nav>
         </div>
        {children}
         <footer className="py-6 text-center bg-white">
        <p className="text-sm">© 2025 Tsuki • Made with 💜</p>
      </footer>

  
      </body>
    </html>
  );
}
